def InsertCountryData(dbConnection):
    cursor = dbConnection.cursor()
    statements = [
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(0, 'Total / No breakdown ', '00')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(1, 'Austria', 'AT')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(2, 'Belgium', 'BE')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(3, 'Bulgaria', 'BG')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(4, 'Cyprus', 'CY')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(5, 'Czech Republic', 'CZ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(6, 'Denmark', 'DK')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(7, 'Estonia', 'EE')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(8, 'Finland', 'FI')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(9, 'France', 'FR')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(10, 'Germany', 'DE')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(11, 'Greece', 'GR')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(12, 'Hungary', 'HU')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(13, 'Iceland', 'IS')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(14, 'Ireland', 'IE')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(15, 'Italy', 'IT')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(16, 'Latvia', 'LV')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(17, 'Liechtenstein', 'LI')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(18, 'Lithuania', 'LT')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(19, 'Luxembourg', 'LU')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(20, 'Malta', 'MT')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(21, 'Netherlands', 'NL')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(22, 'Norway', 'NO')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(23, 'Poland', 'PL')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(24, 'Portugal', 'PT')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(25, 'Romania', 'RO')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(26, 'Slovakia', 'SK')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(27, 'Slovenia', 'SI')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(28, 'Spain', 'ES')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(29, 'Sweden', 'SE')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(30, 'United Kingdom', 'GB')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(31, 'Brazil', 'BR')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(32, 'Chile', 'CL')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(33, 'China', 'CN')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(34, 'CROATIA', 'HR')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(35, 'Hong Kong', 'HK')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(36, 'India', 'IN')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(37, 'Japan', 'JP')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(38, 'Mexico', 'MX')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(39, 'Peru', 'PE')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(40, 'Russian Federation', 'RU')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(41, 'Switzerland', 'CH')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(42, 'Turkey', 'TR')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(43, 'United States', 'US')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(44, 'International organisations', 'IZ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(50, 'Afghanistan', 'AF')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(51, 'Albania', 'AL')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(52, 'Algeria', 'DZ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(53, 'American Samoa', 'AS')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(54, 'Andorra', 'AD')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(55, 'Angola', 'AO')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(56, 'Anguilla', 'AI')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(57, 'Antigua and Barbuda', 'AG')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(58, 'Argentina', 'AR')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(59, 'Armenia', 'AM')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(60, 'Aruba', 'AW')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(61, 'Australia', 'AU')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(62, 'Azerbaijan', 'AZ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(63, 'Bahamas', 'BS')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(64, 'Bahrain', 'BH')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(65, 'Bangladesh', 'BD')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(66, 'Barbados', 'BB')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(67, 'Belarus', 'BY')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(68, 'Belize', 'BZ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(69, 'Benin', 'BJ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(70, 'Bermuda', 'BM')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(71, 'Bhutan', 'BT')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(72, 'Bolivia - Plurinational state of', 'BO')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(73, 'Bonaire - Sint Eustatius and Saba', 'BQ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(74, 'Bosnia and Herzegowina', 'BA')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(75, 'Botswana', 'BW')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(76, 'British Indian Ocean Territory', 'IO')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(77, 'Brunei Darussalam', 'BN')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(78, 'Burkina Faso', 'BF')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(79, 'Burundi', 'BI')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(80, 'Cambodia', 'KH')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(81, 'Cameroon', 'CM')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(82, 'Canada', 'CA')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(83, 'Cape Verde', 'CV')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(84, 'Cayman Islands', 'KY')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(85, 'Central African Republic', 'CF')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(86, 'Chad', 'TD')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(87, 'Channel Islands', 'CS')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(88, 'Colombia', 'CO')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(89, 'Comoros', 'KM')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(90, 'CONGO - The Democratic Republic of the', 'CD')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(91, 'CONGO', 'CG')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(92, 'Cook Islands', 'CK')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(93, 'Costa Rica', 'CR')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(94, 'Cote d_Ivoire', 'CI')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(95, 'Cuba', 'CU')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(96, 'Curacao', 'CW')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(97, 'Djibouti', 'DJ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(98, 'Dominica', 'DM')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(99, 'Dominican Republic', 'DO')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(100, 'Ecuador', 'EC')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(101, 'Egypt', 'EG')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(102, 'El Salvador', 'SV')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(103, 'Equatorial Guinea', 'GQ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(104, 'Eritrea', 'ER')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(105, 'Ethiopia', 'ET')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(106, 'Faroe Islands', 'FO')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(107, 'Falkland Islands (MALVINAS)', 'FK')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(108, 'Fiji', 'FJ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(109, 'French Guiana', 'GF')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(110, 'French Polynesia', 'PF')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(111, 'Macedonia - The former Yugoslav Republic of', 'MK')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(112, 'Gabon', 'GA')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(113, 'Gambia', 'GM')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(114, 'Georgia', 'GE')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(115, 'Ghana', 'GH')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(116, 'Gibraltar', 'GI')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(117, 'Greenland', 'GL')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(118, 'Grenada', 'GD')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(119, 'Guadeloupe', 'GP')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(120, 'Guam', 'GU')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(121, 'Guatemala', 'GT')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(122, 'Guinea', 'GN')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(123, 'Guinea-Bissau', 'GW')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(124, 'Guyana', 'GY')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(125, 'Haiti', 'HT')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(126, 'Holy See (Vatican City State)', 'VA')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(127, 'Honduras', 'HN')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(128, 'Indonesia', 'ID')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(129, 'Iran (Islamic Republic of)', 'IR')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(130, 'Iraq', 'IQ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(131, 'Isle of Man', 'IM')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(132, 'Israel', 'IL')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(133, 'Jamaica', 'JM')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(134, 'Jordan', 'JO')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(135, 'Kazakhstan', 'KZ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(136, 'Kenya', 'KE')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(137, 'Kiribati', 'KI')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(138, 'Korea Dem_People_Rep_of', 'KP')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(139, 'Korea Republic_of', 'KR')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(140, 'Kosovo', 'XK')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(141, 'Kuwait', 'KW')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(142, 'Kyrgyzstan', 'KG')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(143, 'Lao P.D.R.', 'LA')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(144, 'Lebanon', 'LB')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(145, 'Lesotho', 'LS')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(146, 'Liberia', 'LR')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(147, 'Libya', 'LY')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(148, 'Macao', 'MO')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(149, 'Madagascar', 'MG')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(150, 'Malawi', 'MW')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(151, 'Malaysia', 'MY')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(152, 'Maldives', 'MV')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(153, 'Mali', 'ML')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(154, 'Marshall Islands', 'MH')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(155, 'Martinique', 'MQ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(156, 'Mauritania', 'MR')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(157, 'Mauritius', 'MU')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(158, 'Mayotte', 'YT')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(159, 'Micronesia - Federated States of', 'FM')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(160, 'Moldova', 'MD')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(161, 'Monaco', 'MC')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(162, 'Mongolia', 'MN')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(163, 'Montenegro', 'ME')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(164, 'Montserrat', 'MS')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(165, 'Morocco', 'MA')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(166, 'Mozambique', 'MZ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(167, 'Myanmar', 'MM')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(168, 'Namibia', 'NA')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(169, 'Nauru', 'NR')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(170, 'Nepal', 'NP')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(171, 'New Caledonia', 'NC')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(172, 'New Zealand', 'NZ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(173, 'Nicaragua', 'NI')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(174, 'Niger', 'NE')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(175, 'Nigeria', 'NG')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(176, 'Niue', 'NU')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(177, 'Northern Mariana Islands', 'MP')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(178, 'Oman', 'OM')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(179, 'Pakistan', 'PK')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(180, 'Palau', 'PW')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(181, 'Panama', 'PA')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(182, 'Papua New Guinea', 'PG')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(183, 'Paraguay', 'PY')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(184, 'Philippines', 'PH')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(185, 'Pitcairn', 'PN')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(186, 'Puerto Rico', 'PR')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(187, 'Qatar', 'QA')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(188, 'Reunion', 'RE')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(189, 'Rwanda', 'RW')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(190, 'Saint Helena', 'SH')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(191, 'Saint Kitts and Nevis', 'KN')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(192, 'Saint Lucia', 'LC')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(193, 'Saint Martin', 'MF')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(194, 'Saint Vincent and the Grenadines', 'VC')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(195, 'Saint-Pierre and Miquelon', 'PM')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(196, 'Samoa', 'WS')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(197, 'San Marino', 'SM')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(198, 'Sao Tome and Principe', 'ST')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(199, 'Saudi Arabia', 'SA')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(200, 'Senegal', 'SN')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(201, 'Serbia', 'RS')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(202, 'Seychelles', 'SC')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(203, 'Sierra Leone', 'SL')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(204, 'Singapore', 'SG')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(205, 'Sint Maarten', 'SX')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(206, 'Solomon Islands', 'SB')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(207, 'Somalia', 'SO')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(208, 'South Africa', 'ZA')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(209, 'South Sudan', 'SS')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(210, 'Sri Lanka', 'LK')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(211, 'Sudan', 'SD')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(212, 'Suriname', 'SR')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(213, 'Svalbard and Jan Mayen Islands', 'SJ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(214, 'Swaziland', 'SZ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(215, 'Syria', 'SY')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(216, 'Taiwan Province of China', 'TW')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(217, 'Tajikistan', 'TJ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(218, 'Tanzania', 'TZ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(219, 'Thailand', 'TH')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(220, 'Timor-Leste', 'TL')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(221, 'Togo', 'TG')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(222, 'Tokelau', 'TK')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(223, 'Tonga', 'TO')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(224, 'Trinidad and Tobago', 'TT')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(225, 'Tunisia', 'TN')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(226, 'Turkmenistan', 'TM')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(227, 'Turks and Caicos Islands', 'TC')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(228, 'Tuvalu', 'TV')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(229, 'Uganda', 'UG')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(230, 'Ukraine', 'UA')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(231, 'United Arab Emirates', 'AE')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(232, 'United States Minor Outlying Islands', 'UM')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(233, 'Uruguay', 'UY')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(234, 'Uzbekistan', 'UZ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(235, 'Vanuatu', 'VU')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(236, 'Venezuela', 'VE')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(237, 'Vietnam', 'VN')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(238, 'Wallis and Futuna Islands', 'WF')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(239, 'West Bank and Gaza', 'WE')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(240, 'Western Sahara', 'EH')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(241, 'Yemen', 'YE')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(242, 'Zambia', 'ZM')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(243, 'Zimbabwe', 'ZW')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(244, 'Other', 'O1')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(245, 'Other Central and eastern Europe countries non EEA', 'O2')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(246, 'Middle East', 'O3')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(247, 'Latin America and the Caribbean', 'O4')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(248, 'Africa', 'O5')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(249, 'Other advanced economies non EEA', 'O6')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(250, 'NORFOLK ISLAND', 'NF')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(251, 'PALESTINIAN TERRITORY, OCCUPIED', 'PS')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(252, 'SAINT BARTHÉLEMY', 'BL')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(253, 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'GS')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(254, 'VIRGIN ISLANDS, BRITISH', 'VG')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(255, 'VIRGIN ISLANDS, U.S.', 'VI')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(256, 'ÅLAND ISLANDS', 'AX')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(257, 'ANTARCTICA', 'AQ')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(258, 'BOUVET ISLAND', 'BV')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(259, 'CHRISTMAS ISLAND', 'CX')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(260, 'COCOS (KEELING) ISLANDS', 'CC')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(261, 'FRENCH SOUTHERN TERRITORIES', 'TF')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(262, 'GUERNSEY', 'GG')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(263, 'HEARD ISLAND AND MCDONALD ISLANDS', 'HM')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(264, 'JERSEY', 'JE')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(701, 'Banque Centrale des États de l’Afrique de l’Ouest (BCEAO)', '_5O')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(702, 'CASDB (Central African States’ Development Bank)', '_5P')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(703, 'African Development Fund', '_5Q')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(704, 'Asian Development Fund', '_5R')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(705, 'Fonds spécial unifié de développement', '_5S')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(706, 'CABEI (Central American Bank for Economic Integration)', '_5T')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(707, 'ADC (Andean Development Corporation)', '_5U')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(708, 'Other International Organisations (financial institutions)', '_5V')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(709, 'Banque des États de l’Afrique centrale (BEAC)', '_5W')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(710, 'Communauté Économique et Monétaire de l’Afrique Centrale (CEMAC)', '_5X')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(711, 'Eastern Caribbean Currency Union (ECCU)', '_5Y')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(712, 'Other International Financial Organisations n.i.e.', '_5Z')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(713, 'Other International Organisations (non-financial institutions)', '_6A')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(714, 'NATO (North Atlantic Treaty Organisation)', '_6B')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(715, 'Council of Europe', '_6C')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(716, 'ICRC (International Committee of the Red Cross)', '_6D')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(717, 'ESA (European Space Agency)', '_6E')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(718, 'EPO (European Patent Office)', '_6F')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(719, 'EUROCONTROL (European Organisation for the Safety of Air Navigation)', '_6G')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(720, 'EUTELSAT (European Telecommunications Satellite Organisation)', '_6H')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(721, 'West African Economic and Monetary Union (WAEMU)', '_6I')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(722, 'INTELSAT (International Telecommunications Satellite Organisation)', '_6J')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(723, 'EBU/UER (European Broadcasting Union/Union européenne de radio-télévision)', '_6K')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(724, 'EUMETSAT (European Organisation for the Exploitation of Meteorological Satellites)', '_6L')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(725, 'ESO (European Southern Observatory)', '_6M')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(726, 'ECMWF (European Centre for Medium-Range Weather Forecasts)', '_6N')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(727, 'EMBL (European Molecular Biology Laboratory)', '_6O')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(728, 'CERN (European Organisation for Nuclear Research)', '_6P')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(729, 'IOM (International Organisation for Migration)', '_6Q')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(730, 'Islamic Development Bank (IDB)', '_6R')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(731, 'Eurasian Development Bank (EDB)', '_6S')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(732, 'Paris Club Creditor Institutions', '_6T')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(733, 'Council of Europe Development Bank (CEB)', '_6U')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(734, 'Other International Non-Financial Organisations n.i.e.', '_6Z')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(735, 'International Organisations excluding European Union Institutions', '_7Z')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(736, 'International Union of Credit and Investment Insurers', '_8A')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(737, 'Multilateral Lending Agencies', '_9B')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(738, 'International organisations (as pseudo geographic area)', '_1A')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(739, 'United Nations organisations', '_1B')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(740, 'IMF (International Monetary Fund)', '_1C')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(741, 'WTO (World Trade Organisation)', '_1D')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(742, 'IBRD (International Bank for Reconstruction and Development)', '_1E')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(743, 'IDA (International Development Association)', '_1F')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(744, 'Other UN Organisations (includes 1H, 1J-1T)', '_1G')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(745, 'UNESCO (United Nations Educational, Scientific and Cultural Organisation)', '_1H')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(746, 'FAO (Food and Agriculture Organisation)', '_1J')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(747, 'WHO (World Health Organisation)', '_1K')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(748, 'IFAD (International Fund for Agricultural Development)', '_1L')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(749, 'IFC (International Finance Corporation)', '_1M')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(750, 'MIGA (Multilateral Investment Guarantee Agency)', '_1N')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(751, 'UNICEF (United Nations Children’s Fund)', '_1O')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(752, 'UNHCR (United Nations High Commissioner for Refugees)', '_1P')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(753, 'UNRWA (United Nations Relief and Works Agency for Palestine)', '_1Q')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(754, 'IAEA (International Atomic Energy Agency)', '_1R')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(755, 'ILO (International Labour Organisation)', '_1S')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(756, 'ITU (International Telecommunication Union)', '_1T')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(757, 'Rest of UN Organisations n.i.e.', '_1Z')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(758, 'European Union Institutions, Organs and Organisms (excluding ECB)', '_4A')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(759, 'EMS (European Monetary System)', '_4B')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(760, 'EIB (European Investment Bank)', '_4C')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(761, 'EC (European Commission)', '_4D')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(762, 'EDF (European Development Fund)', '_4E')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(763, 'European Central Bank', '_4F')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(764, 'EIF (European Investment Fund)', '_4G')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(765, 'ECSC (European Coal and Steel Community)', '_4H')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(766, 'Neighbourhood Investment Facility', '_4I')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(767, 'FEMIP (Facility for Euro-Mediterranean Investment and Partnership)', '_4V')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(768, 'Other EU Institutions, Organs and Organisms covered by the General budget', '_4J')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(769, 'European Parliament', '_4K')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(770, 'Council of the European Union', '_4L')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(771, 'Court of Justice', '_4M')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(772, 'Court of Auditors', '_4N')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(773, 'European Council', '_4O')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(774, 'Economic and Social Committee', '_4P')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(775, 'Committee of the Regions', '_4Q')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(776, 'EU-Africa Infrastructure Trust Fund', '_4R')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(777, 'European Stability Mechanism (ESM)', '_4S')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(778, 'Joint Committee of the European Supervisory Authorities (ESAs)', '_4T')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(779, 'All the European Union Institutions financed via the EU Budget', '_4W')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(780, 'All the European Union Institutions not financed via the EU Budget', '_4X')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(781, 'All the European Union Institutions', '_4Y')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(782, 'Other small European Union Institutions (Ombudsman, Data Protection Supervisor etc.)', '_4Z')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(783, 'OECD (Organisation for Economic Co-operation and Development)', '_5A')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(784, 'BIS (Bank for International Settlements)', '_5B')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(785, 'IADB (Inter-American Development Bank)', '_5C')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(786, 'AfDB (African Development Bank)', '_5D')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(787, 'AsDB (Asian Development Bank)', '_5E')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(788, 'EBRD (European Bank for Reconstruction and Development)', '_5F')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(789, 'IIC (Inter-American Investment Corporation)', '_5G')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(790, 'NIB (Nordic Investment Bank)', '_5H')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(791, 'Eastern Caribbean Central Bank (ECCB)', '_5I')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(792, 'IBEC (International Bank for Economic Co-operation)', '_5J')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(793, 'IIB (International Investment Bank)', '_5K')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(794, 'CDB (Caribbean Development Bank)', '_5L')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(795, 'AMF (Arab Monetary Fund)', '_5M')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(796, 'BADEA (Banque arabe pour le développement économique en Afrique)', '_5N')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(901, 'Countries not relevant for MKR purposes', 'x5')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(902, 'Not applicable/All geographical areas', 'x0')",
        "INSERT INTO Country(ID, Label, ISO_Code) VALUES(903, 'Other Countries', 'x28')"
    ]
    for statement in statements:
        cursor.execute(statement)
    dbConnection.commit()
